spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
    username: mber
    url: jdbc:mariadb://123.24.142.93:82/hoang-demo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    password: techbro@123
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  application:
    name: oauth2-server
server:
  port: 8091

security:
  jwt:
    token:
      secretKey: hoangit3
